version: "3"
services:
    app:
        build: ./app
        volumes:
            - "./app:/app"
        links:
            - db
        ports:
            - "5001:5001"
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: 'yourpassword'
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro